// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRH.Infra;

#nullable disable

namespace SistemaRH.Infra.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250601020127_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InscricaoProcessos", b =>
                {
                    b.Property<Guid>("InscricaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProcessoSeletivoId")
                        .HasColumnType("int");

                    b.HasKey("InscricaoId", "ProcessoSeletivoId");

                    b.HasIndex("ProcessoSeletivoId");

                    b.ToTable("InscricaoProcessos");
                });

            modelBuilder.Entity("InscricaoVagas", b =>
                {
                    b.Property<Guid>("InscricaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VagaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InscricaoId", "VagaId");

                    b.HasIndex("VagaId");

                    b.ToTable("InscricaoVagas");
                });

            modelBuilder.Entity("SistemaRH.Domain.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailCandidato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCandidato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("SistemaRH.Domain.ProcessoSeletivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("SistemaRH.Domain.Vaga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Salario")
                        .HasColumnType("float");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("InscricaoProcessos", b =>
                {
                    b.HasOne("SistemaRH.Domain.Inscricao", null)
                        .WithMany()
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRH.Domain.ProcessoSeletivo", null)
                        .WithMany()
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InscricaoVagas", b =>
                {
                    b.HasOne("SistemaRH.Domain.Inscricao", null)
                        .WithMany()
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRH.Domain.Vaga", null)
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
